# Generated by Django 4.1.1 on 2022-11-06 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppHowTo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='autor',
        ),
        migrations.AddField(
            model_name='articulo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
