# Generated by Django 4.1.1 on 2022-11-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHowTo', '0002_remove_articulo_autor_articulo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
