# Generated by Django 4.1.1 on 2022-11-07 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppHowTo', '0003_articulo_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='respuesta',
            new_name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
